#ifndef __COMBINER_MODES_H__
#define __COMBINER_MODES_H__

#ifdef _LANGUAGE_C_PLUS_PLUS
extern "C" {
#endif

/* Custom blend modes */
#define G_CC_BLENDPETEMPLERP PRIMITIVE, ENVIRONMENT, TEXEL0, ENVIRONMENT, TEXEL1, TEXEL0, PRIM_LOD_FRAC, TEXEL0
#define G_CC_MODULATEI_SHADE_PRIM2 COMBINED, 0, SHADE, 0, COMBINED, 0, PRIMITIVE, 0

#ifdef _LANGUAGE_C_PLUS_PLUS
}
#endif

#endif /* __COMBINER_MODES_H__ */
